# -*- coding: utf-8 -*-
"""Product cards (no prices — specs only, quote on request). Each spec row: (label_me, value_me, label_en, value_en)."""

TEQ = [
    {"img": "teq-one.webp", "title": "TEQ ONE",
     "kind": {"me": "Fiksni · Takmičarski", "en": "Fixed · Competition"},
     "specs": [("Ploča", "HPL, 6 mm", "Top", "HPL, 6 mm"),
               ("Mrežica", "Pleksiglas, 20 mm", "Net", "Plexi, 20 mm"),
               ("Težina", "148 kg", "Weight", "148 kg"),
               ("Fiksiranje", "Za podlogu", "Fixing", "To the ground")]},
    {"img": "teq-smart.webp", "title": "TEQ SMART",
     "kind": {"me": "Sklopivi · Takmičarski", "en": "Foldable · Competition"},
     "specs": [("Ploča", "HPL, 6 mm", "Top", "HPL, 6 mm"),
               ("Sklapanje", "Gasni amortizeri", "Folding", "Gas springs"),
               ("Težina", "168 kg", "Weight", "168 kg"),
               ("Dodatno", "Solo igra", "Extra", "Solo play")]},
    {"img": "teq-lite.webp", "title": "TEQ LITE",
     "kind": {"me": "Sklopivi · Rekreativni", "en": "Foldable · Recreation"},
     "specs": [("Ploča", "Ojačani poliester", "Top", "Reinforced polyester"),
               ("Mrežica", "Polietilen, 15 mm", "Net", "Polyethylene, 15 mm"),
               ("Težina", "110 kg", "Weight", "110 kg"),
               ("Dodatno", "Točkovi + kočnice", "Extra", "Wheels + brakes")]},
    {"img": "teq-x.webp", "title": "TEQ X",
     "kind": {"me": "Fiksni · Rekreativni", "en": "Fixed · Recreation"},
     "specs": [("Ploča", "Ojačani poliester", "Top", "Reinforced polyester"),
               ("Mrežica", "Polietilen, 15 mm", "Net", "Polyethylene, 15 mm"),
               ("Težina", "85 kg", "Weight", "85 kg"),
               ("Fiksiranje", "Za podlogu", "Fixing", "To the ground")]},
]
TEQ_STRIP = {
    "me": ["Unutra / napolju", "Otporno od −20 °C do +40 °C", "Vodootporno i UV otporno",
           "TÜV SÜD sertifikat", "Garancija 24 mjeseca", "Proizvedeno u EU"],
    "en": ["Indoor / outdoor", "Weather-resistant −20 °C to +40 °C", "Waterproof &amp; UV proof",
           "TÜV SÜD certified", "24-month warranty", "Made in EU"],
}

PANELS = [
    {"img": "panel.webp", "title": {"me": "Interaktivna tabla", "en": "Interactive panel"},
     "kind": {"me": "65″ · 75″ · 86″ DLED", "en": "65″ · 75″ · 86″ DLED"},
     "specs": [("Ekran", "4K UHD, 60 Hz", "Display", "4K UHD, 60 Hz"),
               ("Dodir", "20 tačaka, ±1 mm", "Touch", "20 points, ±1 mm"),
               ("Sistem", "Android 14", "System", "Android 14"),
               ("Memorija", "8 GB / 128 GB", "Memory", "8 GB / 128 GB"),
               ("Zvuk", "2 × 20 W", "Audio", "2 × 20 W")]},
    {"img": "kids-table.webp", "title": {"me": "Interaktivni sto", "en": "Interactive table"},
     "kind": {"me": "Za predškolski uzrast", "en": "For preschool age"},
     "specs": [("Ekran", "32″ Full HD", "Display", "32″ Full HD"),
               ("Dodir", "10 tačaka", "Touch", "10 points"),
               ("Sistem", "Android", "System", "Android"),
               ("Memorija", "4 GB / 32 GB", "Memory", "4 GB / 32 GB"),
               ("Napajanje", "12 V, ≤ 60 W", "Power", "12 V, ≤ 60 W")]},
    {"img": "stand-electric.webp", "title": {"me": "Električni stalak", "en": "Electric stand"},
     "kind": {"me": "Mobilni · Podesiva visina", "en": "Mobile · Height adjustable"},
     "specs": [("Za ekrane", "75″–100″", "Fits", "75″–100″"),
               ("Nosivost", "Do 136 kg", "Load", "Up to 136 kg"),
               ("Hod", "500 mm, električni", "Travel", "500 mm, electric"),
               ("Upravljanje", "Daljinski + dodir", "Control", "Remote + touch"),
               ("VESA", "200×200 – 1000×600", "VESA", "200×200 – 1000×600")]},
    {"img": "stand-mobile.webp", "title": {"me": "Mobilni stalak", "en": "Mobile stand"},
     "kind": {"me": "Podni stalak na točkićima", "en": "Floor stand on castors"},
     "specs": [("Za ekrane", "50″–100″", "Fits", "50″–100″"),
               ("Nosivost", "Do 150 kg", "Load", "Up to 150 kg"),
               ("VESA", "Od 1000×600", "VESA", "From 1000×600"),
               ("Ram", "Čelik", "Frame", "Steel"),
               ("Dodatno", "Dvije police", "Extra", "Two shelves")]},
]
PANELS_STRIP = {
    "me": ["Montaža i konfiguracija", "Obuka korisnika", "Garancija 2 godine", "Tehnička podrška",
           "U kutiji: daljinski, 2 olovke, zidni nosač i kabl"],
    "en": ["Installation &amp; configuration", "User training", "2-year warranty", "Technical support",
           "Remote, 2 pens, wall mount and cable in the box"],
}

PLAY = [
    {"img": "play-towers.webp", "title": {"me": "Tematski tornjevi", "en": "Themed towers"},
     "kind": {"me": "Bubbles · Kinglo · Mega · Dino · Flora Play", "en": "Bubbles · Kinglo · Mega · Dino · Flora Play"},
     "specs": [("Za", "Velike površine za igru", "For", "Large play areas"),
               ("Igra", "Penjanje, tobogani, igra uloga", "Play", "Climbing, sliding, role play"),
               ("Izrada", "Čelik, HPL, rotaciono liveni PE", "Build", "Steel, HPL, rotomoulded PE")]},
    {"img": "play-robinia.webp", "title": {"me": "Drvene linije", "en": "Wood lines"},
     "kind": {"me": "Robinia Play · Eco", "en": "Robinia Play · Eco"},
     "specs": [("Za", "Parkove i prirodno okruženje", "For", "Parks and natural settings"),
               ("Materijal", "Bagremovo drvo (robinija)", "Material", "Robinia hardwood"),
               ("Izgled", "Netretirano, organski oblici", "Look", "Untreated, organic forms")]},
    {"img": "play-compact.webp", "title": {"me": "Kompaktno i pojedinačno", "en": "Compact &amp; single"},
     "kind": {"me": "Mini · Single · Active", "en": "Mini · Single · Active"},
     "specs": [("Za", "Mala dvorišta, vrtiće", "For", "Small yards, preschools"),
               ("Uključuje", "Ljuljaške, klackalice, pješčanike", "Includes", "Swings, springers, sandpits"),
               ("Namjena", "Popunjava ili proširuje lokaciju", "Use", "Fills or extends a site")]},
    {"img": "play-ropes.webp", "title": {"me": "Užad i ravnoteža", "en": "Ropes &amp; balance"},
     "kind": {"me": "Acrobat · Ellipsum · Organiq", "en": "Acrobat · Ellipsum · Organiq"},
     "specs": [("Za", "Stariju djecu, tinejdžere", "For", "Older children, teenagers"),
               ("Igra", "Mreže, ravnoteža, okretanje", "Play", "Net climbing, balance, spinning"),
               ("Izrada", "Čelik i užad", "Build", "Steel and rope structures")]},
    {"img": "play-workout.webp", "title": {"me": "Vježbanje i sport", "en": "Workout &amp; sport"},
     "kind": {"me": "Street Workout · Fitness · Sport", "en": "Street Workout · Fitness · Sport"},
     "specs": [("Za", "Škole, javne prostore", "For", "Schools, public spaces"),
               ("Uključuje", "Kalistenika, outdoor fitness", "Includes", "Calisthenics, outdoor fitness"),
               ("Opcije", "Nerđajući čelik ili robinija", "Options", "Stainless steel or robinia")]},
    {"img": "play-urban.webp", "title": {"me": "Urbani mobilijar", "en": "Urban furniture"},
     "kind": {"me": "Urbaniq · Aquarius Inox", "en": "Urbaniq · Aquarius Inox"},
     "specs": [("Za", "Trgove, šetališta, parkove", "For", "Squares, promenades, parks"),
               ("Uključuje", "Klupe, korpe, igra sa vodom", "Includes", "Benches, bins, water play"),
               ("Materijal", "Nerđajući čelik", "Material", "Stainless steel")]},
]
PLAY_STRIP = {
    "me": ["HDPE paneli, 15 mm", "Rotaciono liveni PE tobogani i krovovi", "Linija od nerđajućeg čelika",
           "Linija od recikliranih materijala", "Inkluzivna oprema", "Prilagođene modifikacije"],
    "en": ["HDPE panels, 15 mm", "Rotomoulded PE slides and roofs", "Stainless steel line",
           "Recycled line", "Inclusive equipment", "Custom modifications"],
}

FITNESS = [
    {"img": "fitness-power.webp", "title": {"me": "Sprave sa tegovima", "en": "Plate-loaded machines"},
     "kind": {"me": "Power linija · Trening snage", "en": "Power line · Strength training"},
     "specs": [("Opterećenje", "Podesivo, tegovi", "Load", "Adjustable, weight plates"),
               ("Vježbe", "Potisak, povlačenje, noge", "Exercises", "Press, pull, legs"),
               ("Konstrukcija", "Čelik", "Frame", "Steel"),
               ("Boja", "Više opcija", "Colour", "Several options")]},
    {"img": "fitness-bench.webp", "title": {"me": "Klupe i stanice", "en": "Benches &amp; stations"},
     "kind": {"me": "Trup · Leđa · Stabilizacija", "en": "Core · Back · Stability"},
     "specs": [("Namjena", "Trup i leđa", "Purpose", "Core and back"),
               ("Nivo", "Od početnika do sportista", "Level", "Beginner to athlete"),
               ("Konstrukcija", "Čelik", "Frame", "Steel")]},
    {"img": "play-workout.webp", "title": {"me": "Street workout", "en": "Street workout"},
     "kind": {"me": "Kalistenika · Buglo Play", "en": "Calisthenics · Buglo Play"},
     "specs": [("Za", "Škole, parkove, kampuse", "For", "Schools, parks, campuses"),
               ("Uključuje", "Vratila, razboj, ljestve, klupe", "Includes", "Bars, dip bars, ladders, benches"),
               ("Opcije", "Nerđajući čelik ili robinija", "Options", "Stainless steel or robinia")]},
    {"img": "fitness-park.webp", "title": {"me": "Kompletan fitness park", "en": "Complete fitness park"},
     "kind": {"me": "Po mjeri lokacije", "en": "Built around the site"},
     "specs": [("Za", "Opštine, kampuse, hotele", "For", "Municipalities, campuses, hotels"),
               ("Projekat", "Raspored po mjeri", "Project", "Custom layout"),
               ("Usluga", "Planiranje i montaža", "Service", "Planning and installation")]},
]
FITNESS_STRIP = {
    "me": ["Za javne prostore", "Upotreba tokom cijele godine", "Podesivo opterećenje",
           "Više boja", "Planiranje i montaža", "Standard EN 16630"],
    "en": ["Built for public spaces", "Year-round use", "Adjustable load",
           "Several colours", "Planning and installation", "EN 16630 standard"],
}
