# -*- coding: utf-8 -*-
"""Landing page content, ME + EN. No prices anywhere; no project/case references."""

LP_COMMON = {
    "me": {
        "why_eyebrow": "Zašto 5TO9", "aud_eyebrow": "Za koga", "aud_h": "ZA KOGA<br>JE OVO.",
        "proc_eyebrow": "Kako radimo", "faq_eyebrow": "Česta pitanja", "faq_h": "PITANJA<br>I ODGOVORI.",
        "ask_eyebrow": "Upit", "ask_h": "ZATRAŽITE<br>PONUDU.", "ask_btn": "Pošaljite upit", "call_btn": "Pozovite",
        "more_eyebrow": "Ostala ponuda", "more_h": "JOŠ IZ<br>5TO9 PONUDE.",
        "see_range": "Pogledajte opremu ↓",
        "procurement_q": "Da li radite sa javnim nabavkama?",
        "procurement_a": "Da. Radimo sa školama, opštinama i institucijama, uključujući postupke javnih nabavki, i pripremamo potrebnu tehničku dokumentaciju.",
        "quote_q": "Kako da dobijem cijenu?",
        "mail_body": "Poštovani,\n\nzanima nas: {cat}\n\nUstanova / firma:\nGrad:\nKoličina / veličina prostora:\nŽeljeni rok:\n\nPoruka:\n",
    },
    "en": {
        "why_eyebrow": "Why 5TO9", "aud_eyebrow": "Who it's for", "aud_h": "WHO IT'S<br>FOR.",
        "proc_eyebrow": "How we work", "faq_eyebrow": "FAQ", "faq_h": "QUESTIONS<br>&amp; ANSWERS.",
        "ask_eyebrow": "Enquiry", "ask_h": "REQUEST<br>A QUOTE.", "ask_btn": "Send an enquiry", "call_btn": "Call us",
        "more_eyebrow": "More from 5TO9", "more_h": "THE REST<br>OF THE RANGE.",
        "see_range": "See the range ↓",
        "procurement_q": "Do you work with public procurement?",
        "procurement_a": "Yes. We work with schools, municipalities and institutions, including public procurement procedures, and prepare the technical documentation they require.",
        "quote_q": "How do I get a price?",
        "mail_body": "Hello,\n\nWe are interested in: {cat}\n\nOrganisation:\nCity:\nQuantity / size of the space:\nPreferred timeline:\n\nMessage:\n",
    },
}

LP = {
# ------------------------------------------------------------------ TEQBALL
"teqball": {
    "products": "TEQ", "strip": "TEQ_STRIP", "hero_img": "teq-court.jpg", "og": "og-teq.jpg", "models_cls": "models",
    "me": {
        "title": "Teqball stolovi — TEQ ONE, SMART, LITE i X | 5TO9 Crna Gora",
        "desc": "Teqball stolovi za škole, opštine, klubove i hotele u Crnoj Gori. Modeli TEQ ONE, TEQ SMART, TEQ LITE i TEQ X — isporuka, montaža i podrška. Zatražite ponudu.",
        "hero_alt": "TEQ sto pored osvijetljenog sportskog terena u Podgorici",
        "eyebrow": "Sportska oprema · TEQ",
        "h1": "TEQBALL<br><em>STOLOVI</em>",
        "lead": "Zakrivljeni TEQ stolovi za škole, opštine, sportske klubove i hotele — isporučeni, postavljeni i spremni za igru. Jedan sto, pet sportova: teqball, teqvoly, teqpong, qatch i para teqball.",
        "facts": ["300+ instaliranih stolova", "4 modela", "TÜV SÜD sertifikat", "Garancija 24 mj."],
        "ticker": ["Teqball", "Teqvoly", "Teqpong", "Qatch", "Para teqball"],
        "why_h": "JEDAN STO,<br>PET SPORTOVA.",
        "benefits": [
            ("Pet sportova na jednom stolu", "Zakrivljena površina otvara teqball, teqvoly, teqpong, qatch i para teqball — za nastavu fizičkog, rekreaciju i takmičenja."),
            ("Unutra i napolju", "Vodootporni i UV otporni stolovi, za temperature od −20 °C do +40 °C. Sto ostaje na terenu tokom cijele godine."),
            ("Provjeren kvalitet", "Stolovi su TÜV SÜD sertifikovani i proizvedeni u EU, uz garanciju od 24 mjeseca."),
            ("Isporuka i montaža", "Dovozimo, postavljamo i fiksiramo sto na lokaciji, i pomažemo da zaživi u školi ili zajednici."),
        ],
        "range_eyebrow": "Modeli · TEQ",
        "range_h": "ZAKRIVLJENI STO,<br>ČETIRI MODELA.",
        "range_p": "Svaki model je dimenzija 3 × 1,5 m i visine 0,76 m, za unutrašnju i spoljašnju upotrebu. Izbor zavisi od toga da li sto stoji fiksno ili se pomjera i da li služi za takmičenja ili rekreaciju.",
        "aud": [
            ("Škole", "Nastava fizičkog vaspitanja, sekcije i školska takmičenja."),
            ("Opštine i javni prostori", "Parkovi, sportski tereni i šetališta — fiksni modeli za spoljašnju upotrebu."),
            ("Klubovi i akademije", "Takmičarski modeli za treninge i turnire."),
            ("Hoteli i turizam", "Sadržaj za goste na plaži, uz bazen ili u sportskoj zoni."),
        ],
        "proc_h": "OD UPITA<br>DO PRVOG MEČA.",
        "steps": [
            ("Izbor modela", "Na osnovu lokacije i namjene predlažemo fiksni ili sklopivi, takmičarski ili rekreativni model."),
            ("Ponuda", "Šaljemo ponudu sa tehničkom specifikacijom, rokom isporuke i uslovima."),
            ("Isporuka i montaža", "Dovozimo sto i postavljamo ga na lokaciji; fiksne modele pričvršćujemo za podlogu."),
            ("Aktivacija", "Pokazujemo kako se sto koristi i pomažemo da zaživi kroz igru i takmičenja."),
        ],
        "faq": [
            ("Koliko prostora je potrebno za teqball sto?", "Sam sto zauzima 3 × 1,5 m, a oko njega je potrebna slobodna zona za kretanje igrača. Pri izboru lokacije pomažemo da odredite odgovarajući prostor."),
            ("Koja je razlika između TEQ ONE i TEQ X?", "Oba modela su fiksna. TEQ ONE ima HPL ploču od 6 mm i mrežicu od pleksiglasa od 20 mm i namijenjen je takmičenjima; TEQ X ima ploču od ojačanog poliestera i polietilensku mrežicu i namijenjen je rekreaciji."),
            ("Mogu li stolovi stajati napolju tokom cijele godine?", "Da. Svi modeli su za unutrašnju i spoljašnju upotrebu, vodootporni i UV otporni, za temperature od −20 °C do +40 °C."),
            ("Da li nudite i montažu?", "Da. Isporuka, postavljanje i fiksiranje stola dio su naše usluge, uz podršku u korišćenju."),
            ("__procurement__", ""),
            ("__quote__", "Cijena zavisi od modela, količine i lokacije. Pošaljite upit sa osnovnim podacima i odgovaramo sa ponudom."),
        ],
        "ask_p": "Recite nam lokaciju, namjenu i broj stolova — odgovaramo sa prijedlogom modela i ponudom.",
        "mail_cat": "Teqball stolovi",
    },
    "en": {
        "title": "Teqball tables — TEQ ONE, SMART, LITE and X | 5TO9 Montenegro",
        "desc": "Teqball tables for schools, municipalities, clubs and hotels in Montenegro. TEQ ONE, TEQ SMART, TEQ LITE and TEQ X — delivery, installation and support. Request a quote.",
        "hero_alt": "TEQ table beside a floodlit sports court in Podgorica",
        "eyebrow": "Sports equipment · TEQ",
        "h1": "TEQBALL<br><em>TABLES</em>",
        "lead": "Curved TEQ tables for schools, municipalities, sports clubs and hotels — delivered, installed and ready to play. One table, five sports: teqball, teqvoly, teqpong, qatch and para teqball.",
        "facts": ["300+ tables installed", "4 models", "TÜV SÜD certified", "24-month warranty"],
        "ticker": ["Teqball", "Teqvoly", "Teqpong", "Qatch", "Para teqball"],
        "why_h": "ONE TABLE,<br>FIVE SPORTS.",
        "benefits": [
            ("Five sports on one table", "The curved surface opens up teqball, teqvoly, teqpong, qatch and para teqball — for PE lessons, recreation and competition."),
            ("Indoors and out", "Waterproof and UV-proof tables rated from −20 °C to +40 °C. The table stays on the court all year."),
            ("Proven quality", "TÜV SÜD certified and made in the EU, with a 24-month warranty."),
            ("Delivery and installation", "We deliver, set up and anchor the table on site, and help it take off in the school or community."),
        ],
        "range_eyebrow": "Models · TEQ",
        "range_h": "THE CURVED<br>TABLE, FOUR WAYS.",
        "range_p": "Every model is 3 × 1.5 m at 0.76 m height, built for indoor and outdoor use. The choice comes down to whether the table stays put or moves, and whether it is used for competition or recreation.",
        "aud": [
            ("Schools", "PE lessons, after-school clubs and school competitions."),
            ("Municipalities and public spaces", "Parks, sports grounds and promenades — fixed models for outdoor use."),
            ("Clubs and academies", "Competition models for training and tournaments."),
            ("Hotels and tourism", "Something for guests to play on the beach, by the pool or in the sports area."),
        ],
        "proc_h": "FROM ENQUIRY<br>TO FIRST MATCH.",
        "steps": [
            ("Choosing the model", "Based on the site and its use, we recommend a fixed or foldable, competition or recreation model."),
            ("Quote", "We send a quote with the technical specification, delivery time and terms."),
            ("Delivery and installation", "We deliver the table and set it up on site; fixed models are anchored to the ground."),
            ("Activation", "We show how the table is used and help it take off through play and competitions."),
        ],
        "faq": [
            ("How much space does a teqball table need?", "The table itself is 3 × 1.5 m, and it needs a clear zone around it for players to move. We help you pick a suitable spot when choosing the location."),
            ("What is the difference between TEQ ONE and TEQ X?", "Both are fixed models. TEQ ONE has a 6 mm HPL top and a 20 mm plexi net and is built for competition; TEQ X has a reinforced polyester top and a polyethylene net and is built for recreation."),
            ("Can the tables stay outdoors all year?", "Yes. All models are made for indoor and outdoor use, waterproof and UV-proof, and rated from −20 °C to +40 °C."),
            ("Do you install the tables?", "Yes. Delivery, set-up and anchoring are part of our service, together with support in using the table."),
            ("__procurement__", ""),
            ("__quote__", "The price depends on the model, quantity and location. Send an enquiry with the basics and we will reply with a quote."),
        ],
        "ask_p": "Tell us the location, the use and how many tables you need — we reply with a recommended model and a quote.",
        "mail_cat": "Teqball tables",
    },
},
# ------------------------------------------------------------------ PANELS
"panels": {
    "products": "PANELS", "strip": "PANELS_STRIP", "hero_img": "panel.webp", "og": "og-panels.jpg", "models_cls": "models",
    "me": {
        "title": "Interaktivne table za škole i firme — 65″, 75″, 86″ | 5TO9 Crna Gora",
        "desc": "Interaktivne table 65″, 75″ i 86″ (4K, Android 14) za škole, vrtiće, institucije i firme u Crnoj Gori. Montaža, obuka i garancija 2 godine uključeni. Zatražite ponudu.",
        "hero_alt": "Učenici i nastavnica rade na interaktivnoj tabli u učionici",
        "eyebrow": "Digitalna rješenja · GAOKEview",
        "h1": "INTERAKTIVNE<br><em>TABLE</em>",
        "lead": "Table koje stižu podešene, montirane i spremne za prvi čas. Uz svaku tablu: montaža, obuka zaposlenih, garancija 2 godine i tehnička podrška.",
        "facts": ["100+ instaliranih tabli", "65″ · 75″ · 86″", "4K · Android 14", "Garancija 2 godine"],
        "ticker": ["Osnovne škole", "Srednje škole", "Vrtići", "Institucije", "Sale za sastanke"],
        "why_h": "SPREMNO<br>ZA ČAS.",
        "benefits": [
            ("Spremno od prvog dana", "Tabla se isporučuje konfigurisana i montirana — nastavnik je koristi odmah."),
            ("Obuka uključena", "Organizujemo obuku za nastavnike i zaposlene, da se tabla koristi svakodnevno, a ne povremeno."),
            ("Lokalna podrška", "Tehnička podrška tokom garantnog roka od 2 godine, od tima iz Podgorice."),
            ("Sve u kutiji", "Daljinski upravljač, dvije olovke, zidni nosač i kabl dolaze uz svaku tablu."),
        ],
        "range_eyebrow": "Oprema · GAOKEview",
        "range_h": "TABLE, STOLOVI<br>I NOSAČI.",
        "range_p": "Interaktivne table u tri veličine, interaktivni sto za najmlađe i stalci za učionice bez zida za montažu.",
        "aud": [
            ("Osnovne i srednje škole", "Interaktivna nastava, prezentacije i rad u grupama u svakoj učionici."),
            ("Vrtići", "Interaktivni sto od 32″ prilagođen predškolskom uzrastu."),
            ("Institucije", "Sale za sastanke, obuke i javne prezentacije."),
            ("Firme", "Prezentacije, sastanci i obuke bez projektora i dodatne opreme."),
        ],
        "proc_h": "OD UPITA<br>DO PRVOG ČASA.",
        "steps": [
            ("Procjena", "Utvrđujemo broj učionica ili prostorija, veličinu table i način montaže — na zid ili na stalak."),
            ("Ponuda", "Šaljemo ponudu sa specifikacijom i rokom isporuke."),
            ("Montaža", "Montiramo i podešavamo table na lokaciji."),
            ("Obuka", "Obučavamo korisnike i ostajemo na raspolaganju za podršku."),
        ],
        "faq": [
            ("Koje veličine table nudite?", "65″, 75″ i 86″ — sve sa 4K UHD DLED ekranom i dodirom na 20 tačaka."),
            ("Da li je potreban računar?", "Ne. Tabla ima ugrađen Android 14 sa 8 GB RAM i 128 GB memorije i radi samostalno. Po potrebi se na nju može povezati i računar."),
            ("Šta je uključeno?", "Montaža i konfiguracija, obuka korisnika, garancija 2 godine i tehnička podrška. U kutiji su daljinski upravljač, dvije olovke, zidni nosač i kabl."),
            ("Može li tabla biti na pokretnom stalku?", "Da. Nudimo mobilni stalak na točkićima (50″–100″) i električni stalak sa podesivom visinom (75″–100″)."),
            ("__procurement__", ""),
            ("__quote__", "Cijena zavisi od veličine table, količine i načina montaže. Pošaljite upit i odgovaramo sa ponudom."),
        ],
        "ask_p": "Recite nam koliko učionica ili prostorija opremate i koju veličinu table razmatrate — odgovaramo sa ponudom.",
        "mail_cat": "Interaktivne table",
    },
    "en": {
        "title": "Interactive displays for schools and offices — 65″, 75″, 86″ | 5TO9 Montenegro",
        "desc": "65″, 75″ and 86″ interactive displays (4K, Android 14) for schools, preschools, institutions and companies in Montenegro. Installation, training and a 2-year warranty included.",
        "hero_alt": "Pupils and a teacher working at an interactive display in a classroom",
        "eyebrow": "Digital solutions · GAOKEview",
        "h1": "INTERACTIVE<br><em>DISPLAYS</em>",
        "lead": "Panels that arrive configured, mounted and ready for the first lesson. Every panel comes with installation, staff training, a 2-year warranty and technical support.",
        "facts": ["100+ panels installed", "65″ · 75″ · 86″", "4K · Android 14", "2-year warranty"],
        "ticker": ["Primary schools", "Secondary schools", "Preschools", "Institutions", "Meeting rooms"],
        "why_h": "READY FOR<br>THE LESSON.",
        "benefits": [
            ("Ready from day one", "The panel is delivered configured and mounted — teachers use it straight away."),
            ("Training included", "We train teachers and staff so the panel is used every day, not now and then."),
            ("Local support", "Technical support throughout the 2-year warranty, from our team in Podgorica."),
            ("Everything in the box", "Remote control, two pens, wall mount and cable come with every panel."),
        ],
        "range_eyebrow": "Equipment · GAOKEview",
        "range_h": "PANELS, TABLES<br>AND STANDS.",
        "range_p": "Interactive panels in three sizes, an interactive table for the youngest, and stands for rooms without a wall to mount on.",
        "aud": [
            ("Primary and secondary schools", "Interactive lessons, presentations and group work in every classroom."),
            ("Preschools", "A 32″ interactive table made for preschool age."),
            ("Institutions", "Meeting rooms, training sessions and public presentations."),
            ("Companies", "Presentations, meetings and training without a projector or extra kit."),
        ],
        "proc_h": "FROM ENQUIRY<br>TO FIRST LESSON.",
        "steps": [
            ("Assessment", "We confirm the number of rooms, the panel size and the mounting — wall or stand."),
            ("Quote", "We send a quote with the specification and delivery time."),
            ("Installation", "We mount and configure the panels on site."),
            ("Training", "We train the users and stay available for support."),
        ],
        "faq": [
            ("Which sizes do you offer?", "65″, 75″ and 86″ — all with a 4K UHD DLED screen and 20-point touch."),
            ("Do I need a computer?", "No. The panel runs Android 14 with 8 GB RAM and 128 GB storage and works on its own. A computer can be connected when needed."),
            ("What is included?", "Installation and configuration, user training, a 2-year warranty and technical support. The box contains a remote, two pens, a wall mount and a cable."),
            ("Can the panel go on a mobile stand?", "Yes. We offer a mobile stand on castors (50″–100″) and an electric height-adjustable stand (75″–100″)."),
            ("__procurement__", ""),
            ("__quote__", "The price depends on the panel size, quantity and mounting. Send an enquiry and we will reply with a quote."),
        ],
        "ask_p": "Tell us how many classrooms or rooms you are equipping and which panel size you have in mind — we reply with a quote.",
        "mail_cat": "Interactive displays",
    },
},
# ------------------------------------------------------------------ PLAYGROUNDS
"playgrounds": {
    "products": "PLAY", "strip": "PLAY_STRIP", "hero_img": "playground.jpg", "og": "og-play.jpg", "models_cls": "models models-3",
    "me": {
        "title": "Dječija igrališta — oprema, planiranje i montaža | 5TO9 Crna Gora",
        "desc": "Oprema za dječija igrališta za vrtiće, škole, opštine i hotele u Crnoj Gori. Više od 20 linija Buglo Play opreme sertifikovane po EN 1176. Planiranje i montaža.",
        "hero_alt": "Djeca se igraju na inkluzivnom igralištu",
        "eyebrow": "Igrališta · Buglo Play",
        "h1": "DJEČIJA<br><em>IGRALIŠTA</em>",
        "lead": "Od jedne klackalice do kompletnog tematskog igrališta — biramo opremu, planiramo raspored i montiramo igralište prilagođeno prostoru i djeci koja će ga koristiti.",
        "facts": ["20+ linija proizvoda", "EN 1176 · TÜV SÜD", "Inkluzivna oprema", "Prilagođene modifikacije"],
        "ticker": ["Vrtići", "Škole", "Parkovi", "Stambeni kompleksi", "Hoteli"],
        "why_h": "IGRA KOJA<br>TRAJE.",
        "benefits": [
            ("Bezbjednost na prvom mjestu", "Svaki proizvod je sertifikovan prema evropskom standardu EN 1176, uz sertifikate koje izdaje TÜV SÜD."),
            ("Igralište za svako dijete", "Inkluzivna oprema omogućava zajedničku igru djeci različitih sposobnosti."),
            ("Materijali koji traju", "HDPE paneli od 15 mm, rotaciono liveni PE tobogani, nerđajući čelik i bagremovo drvo."),
            ("Od ideje do otvaranja", "Planiramo raspored, biramo opremu i montiramo igralište — jedan partner za cijeli projekat."),
        ],
        "range_eyebrow": "Oprema · Buglo Play",
        "range_h": "IGRALIŠTA,<br>LINIJU PO LINIJU.",
        "range_p": "Katalog sa više od dvadeset linija proizvoda, od jedne klackalice na opruzi do kompletnog tematskog tornja — uz prilagođene modifikacije kada lokacija traži nešto što još ne postoji.",
        "aud": [
            ("Vrtići", "Kompaktna oprema za mala dvorišta i najmlađi uzrast."),
            ("Škole", "Igrališta i zone za igru za odmore i vannastavne aktivnosti."),
            ("Opštine i parkovi", "Tematska i inkluzivna igrališta za javne prostore."),
            ("Hoteli i stambeni kompleksi", "Igralište kao dodatna vrijednost za goste i stanare."),
        ],
        "proc_h": "OD SKICE<br>DO OTVARANJA.",
        "steps": [
            ("Obilazak lokacije", "Upoznajemo prostor, uzrast korisnika i okvir projekta."),
            ("Idejno rješenje", "Predlažemo opremu i raspored igrališta, uz tehničke specifikacije."),
            ("Isporuka i montaža", "Isporučujemo opremu i montiramo igralište na lokaciji."),
            ("Otvaranje", "Predajemo igralište spremno za korišćenje i pomažemo u promociji otvaranja."),
        ],
        "faq": [
            ("Da li je oprema sertifikovana?", "Da. Svaki proizvod je sertifikovan u skladu sa evropskim standardom EN 1176:2017, a sertifikate izdaje TÜV SÜD."),
            ("Možete li opremiti mali prostor?", "Da. Kompaktne linije (Mini, Single, Active) namijenjene su malim dvorištima i vrtićima, a mogu i da dopune postojeće igralište."),
            ("Imate li opremu za djecu sa invaliditetom?", "Da. U ponudi je inkluzivna oprema koja omogućava zajedničku igru djeci različitih sposobnosti."),
            ("Može li oprema da se prilagodi lokaciji?", "Da. Proizvođač radi prilagođene modifikacije kada lokacija traži rješenje kojeg nema u katalogu."),
            ("__procurement__", ""),
            ("__quote__", "Cijena zavisi od izbora opreme, veličine igrališta i lokacije. Pošaljite upit i odgovaramo sa prijedlogom i ponudom."),
        ],
        "ask_p": "Pošaljite nam lokaciju, približnu veličinu prostora i uzrast djece — odgovaramo sa prijedlogom opreme i ponudom.",
        "mail_cat": "Dječija igrališta",
    },
    "en": {
        "title": "Children's playgrounds — equipment, planning and installation | 5TO9 Montenegro",
        "desc": "Playground equipment for preschools, schools, municipalities and hotels in Montenegro. More than 20 Buglo Play lines certified to EN 1176. Planning and installation.",
        "hero_alt": "Children playing on an inclusive playground",
        "eyebrow": "Playgrounds · Buglo Play",
        "h1": "CHILDREN'S<br><em>PLAYGROUNDS</em>",
        "lead": "From a single spring rider to a complete themed playground — we choose the equipment, plan the layout and install a playground shaped around the space and the children who will use it.",
        "facts": ["20+ product lines", "EN 1176 · TÜV SÜD", "Inclusive equipment", "Custom modifications"],
        "ticker": ["Preschools", "Schools", "Parks", "Residential complexes", "Hotels"],
        "why_h": "PLAY THAT<br>LASTS.",
        "benefits": [
            ("Safety first", "Every product is certified to the European EN 1176 standard, with certificates issued by TÜV SÜD."),
            ("A playground for every child", "Inclusive equipment lets children of different abilities play together."),
            ("Materials that last", "15 mm HDPE panels, rotomoulded PE slides, stainless steel and robinia wood."),
            ("From idea to opening", "We plan the layout, choose the equipment and install the playground — one partner for the whole project."),
        ],
        "range_eyebrow": "Equipment · Buglo Play",
        "range_h": "PLAYGROUNDS,<br>LINE BY LINE.",
        "range_p": "A catalogue of more than twenty product lines, from a single spring rider to a full themed play tower — plus custom modifications when the site asks for something that does not exist yet.",
        "aud": [
            ("Preschools", "Compact equipment for small yards and the youngest children."),
            ("Schools", "Playgrounds and play zones for breaks and after-school activities."),
            ("Municipalities and parks", "Themed and inclusive playgrounds for public spaces."),
            ("Hotels and residential complexes", "A playground as added value for guests and residents."),
        ],
        "proc_h": "FROM SKETCH<br>TO OPENING DAY.",
        "steps": [
            ("Site visit", "We get to know the space, the age of the users and the scope of the project."),
            ("Concept design", "We propose the equipment and layout, with technical specifications."),
            ("Delivery and installation", "We deliver the equipment and install the playground on site."),
            ("Opening", "We hand over a playground ready for use and help promote the opening."),
        ],
        "faq": [
            ("Is the equipment certified?", "Yes. Every product is certified to the European EN 1176:2017 standard, with certificates issued by TÜV SÜD."),
            ("Can you equip a small space?", "Yes. The compact lines (Mini, Single, Active) are made for small yards and preschools, and can also extend an existing playground."),
            ("Do you have equipment for children with disabilities?", "Yes. The range includes inclusive equipment that lets children of different abilities play together."),
            ("Can the equipment be adapted to the site?", "Yes. The manufacturer makes custom modifications when a site needs something that is not in the catalogue."),
            ("__procurement__", ""),
            ("__quote__", "The price depends on the equipment, the size of the playground and the location. Send an enquiry and we will reply with a proposal and a quote."),
        ],
        "ask_p": "Send us the location, the approximate size of the space and the children's age group — we reply with an equipment proposal and a quote.",
        "mail_cat": "Children's playgrounds",
    },
},
# ------------------------------------------------------------------ OUTDOOR FITNESS
"fitness": {
    "products": "FITNESS", "strip": "FITNESS_STRIP", "hero_img": "fitness-hero.jpg", "og": "og-fitness.jpg", "models_cls": "models models-3",
    "gallery": ["gal-orange.webp", "gal-red.webp", "gal-yellow.webp", "gal-green.webp", "gal-blue.webp", "gal-yellow2.webp"],
    "me": {
        "title": "Outdoor fitness — StreetBarbell sprave sa tegovima | 5TO9 Crna Gora",
        "desc": "Outdoor teretane StreetBarbell (Finska) za opštine, škole, hotele i stambene komplekse u Crnoj Gori: sprave sa patentiranim sistemom tegova, street workout, inkluzivna i dječija oprema. Sertifikat EN 16630.",
        "hero_alt": "Red narandžastih StreetBarbell sprava za trening snage na otvorenom",
        "eyebrow": "Sportska oprema · StreetBarbell",
        "h1": "OUTDOOR<br><em>FITNESS</em>",
        "lead": "Teretana na otvorenom sa pravim tegovima. Finska StreetBarbell oprema, ispitana po standardu EN 16630 — planiramo, isporučujemo i montiramo za opštine, škole, hotele i stambene komplekse.",
        "facts": ["Patentirani sistem tegova", "EN 16630 · TÜV Thüringen", "9 linija opreme", "Do 10 god. garancije na ram"],
        "ticker": ["Outdoor teretane", "Street workout", "Kalistenika", "Inkluzivne sprave", "Parkovi", "Kampusi"],
        "why_h": "TERETANA<br>BEZ KROVA.",
        "benefits": [
            ("Patentirani sistem tegova", "Opterećenje se podešava tegovima direktno na spravi — pravi trening snage napolju, za početnike i sportiste. Sistem je 2016. bio nominovan za nagradu za inovaciju na sajmu FIBO."),
            ("Ispitano po EN 16630", "TÜV Thüringen je ispitao Standard, Light, Plus i Workout linije po standardu DIN EN 16630 za trajno montiranu opremu za vježbanje na otvorenom."),
            ("Napravljeno za napolje", "Čelični ram sa zaštitom od korozije, nerđajući čelik, zaptiveni ležajevi i sjedišta od izdržljivog poliuretana. Garancija na ram do 10 godina."),
            ("Video uputstvo na spravi", "Na svakoj spravi je tabla sa vježbama i QR kodom koji vodi do video lekcija profesionalnih trenera."),
        ],
        "range_eyebrow": "Oprema · StreetBarbell",
        "range_h": "DEVET LINIJA,<br>JEDAN PARK.",
        "range_p": "Od sprava sa tegovima i street workout konstrukcija do opreme za djecu i korisnike u invalidskim kolicima — kombinujemo linije prema prostoru i korisnicima.",
        "gallery_eyebrow": "Boje",
        "gallery_h": "U BOJI<br>VAŠEG PROSTORA.",
        "gallery_p": "Ram i pokretni djelovi mogu biti u istoj ili kontrastnoj boji — standardne RAL boje ili bilo koja RAL boja po dogovoru. Zaštita: plastifikacija, termoplastika ili vruće cinkovanje.",
        "gallery_alt": "StreetBarbell sprave u boji",
        "aud": [
            ("Opštine", "Outdoor teretane u parkovima, na šetalištima i uz sportske terene."),
            ("Škole i fakulteti", "Street workout i trening snage za učenike, studente i sekcije; Kids linija za najmlađe."),
            ("Inkluzija i rehabilitacija", "Plus linija sa sklopivim sjedištem, za korisnike u invalidskim kolicima."),
            ("Hoteli i resorti", "Teretana na otvorenom kao sadržaj za goste."),
            ("Stambeni kompleksi i firme", "Zajednički prostor za vježbanje stanara i zaposlenih."),
        ],
        "proc_h": "OD PRAZNOG PROSTORA<br>DO PRVOG TRENINGA.",
        "steps": [
            ("Lokacija", "Procjenjujemo prostor, podlogu i očekivani broj korisnika."),
            ("Linije i boje", "Predlažemo kombinaciju sprava, raspored zone i boje rama i pokretnih djelova."),
            ("Montaža", "Sprave postavljamo na betonske ploče ili blok temelje; Light linija može i bez ankerisanja."),
            ("Održavanje", "Uz predaju dobijate plan održavanja — pregled i servis preporučuju se dva puta godišnje."),
        ],
        "faq": [
            ("Da li je oprema sertifikovana?", "Da. Standard, Light, Plus i Workout linije ispitane su po standardu DIN EN 16630 za trajno montiranu opremu za vježbanje na otvorenom (TÜV Thüringen, sertifikat br. 3510.02586.Z01). Dokumentaciju za izabrane sprave dostavljamo uz ponudu."),
            ("Kako funkcioniše sistem tegova?", "Svaka sprava ima tegove koji se podešavaju direktno na njoj, pa korisnik bira opterećenje kao u teretani — od lakog do ozbiljnog trening snage. Sistem je patentiran."),
            ("Koja je garancija?", "Na ram 5 godina (plastifikacija ili termoplastika), odnosno 10 godina uz vruće cinkovanje; na pokretne metalne djelove 3 godine. Garancija važi uz redovno održavanje po uputstvu proizvođača."),
            ("Mogu li da biram boju?", "Da. Sprave se rade u standardnim RAL bojama, a po dogovoru i u bilo kojoj RAL boji. Ram i pokretni djelovi biraju se odvojeno."),
            ("Ima li opreme za osobe sa invaliditetom?", "Da. Plus linija (9 sprava) ima fiksno sklopivo sjedište, pa je mogu koristiti i korisnici u invalidskim kolicima."),
            ("Kakva podloga je potrebna?", "Sprave se postavljaju na betonske ploče ili blok temelje ispod stopa; Light linija može i bez ankerisanja. Tačno rješenje određujemo nakon obilaska lokacije."),
            ("__procurement__", ""),
            ("__quote__", "Cijena zavisi od izbora sprava, njihovog broja, završne obrade i lokacije. Pošaljite upit i odgovaramo sa prijedlogom i ponudom."),
        ],
        "ask_p": "Pošaljite nam lokaciju, veličinu prostora i kome je namijenjen — odgovaramo sa prijedlogom sprava, rasporedom i ponudom.",
        "mail_cat": "Outdoor fitness (StreetBarbell)",
    },
    "en": {
        "title": "Outdoor fitness — StreetBarbell plate-loaded equipment | 5TO9 Montenegro",
        "desc": "StreetBarbell (Finland) outdoor gyms for municipalities, schools, hotels and residential complexes in Montenegro: patented plate-loaded machines, street workout, inclusive and kids' equipment. EN 16630 certified.",
        "hero_alt": "A row of orange StreetBarbell outdoor strength machines",
        "eyebrow": "Sports equipment · StreetBarbell",
        "h1": "OUTDOOR<br><em>FITNESS</em>",
        "lead": "An open-air gym with real weights. Finnish StreetBarbell equipment, tested to EN 16630 — we plan, supply and install it for municipalities, schools, hotels and residential complexes.",
        "facts": ["Patented weight system", "EN 16630 · TÜV Thüringen", "9 equipment lines", "Up to 10-year frame warranty"],
        "ticker": ["Outdoor gyms", "Street workout", "Calisthenics", "Inclusive equipment", "Parks", "Campuses"],
        "why_h": "A GYM<br>WITHOUT A ROOF.",
        "benefits": [
            ("Patented weight system", "Resistance is set with weight plates right on the machine — real strength training outdoors, for beginners and athletes. The system was nominated for the FIBO Innovation Award in 2016."),
            ("Tested to EN 16630", "TÜV Thüringen tested the Standard, Light, Plus and Workout lines to DIN EN 16630 for permanently installed outdoor fitness equipment."),
            ("Built for outdoors", "Corrosion-protected steel frame, stainless steel, sealed bearings and high-strength polyurethane seats. Up to 10 years' frame warranty."),
            ("Video guide on every machine", "Each machine carries an exercise sign with a QR code linking to video lessons from professional trainers."),
        ],
        "range_eyebrow": "Equipment · StreetBarbell",
        "range_h": "NINE LINES,<br>ONE PARK.",
        "range_p": "From plate-loaded machines and street workout structures to equipment for children and wheelchair users — we combine the lines around the space and its users.",
        "gallery_eyebrow": "Colours",
        "gallery_h": "IN THE COLOURS<br>OF YOUR SPACE.",
        "gallery_p": "Frame and moving parts can match or contrast — standard RAL colours or any RAL colour on request. Finish: powder coating, thermoplastic or hot-dip galvanising.",
        "gallery_alt": "StreetBarbell machines in colour",
        "aud": [
            ("Municipalities", "Outdoor gyms in parks, on promenades and next to sports grounds."),
            ("Schools and universities", "Street workout and strength training for pupils, students and clubs; the Kids line for the youngest."),
            ("Inclusion and rehabilitation", "The Plus line with a folding seat, for wheelchair users."),
            ("Hotels and resorts", "An open-air gym as a guest amenity."),
            ("Residential complexes and companies", "A shared training space for residents and staff."),
        ],
        "proc_h": "FROM EMPTY SPACE<br>TO FIRST WORKOUT.",
        "steps": [
            ("Site", "We assess the space, the surface and the expected number of users."),
            ("Lines and colours", "We propose the mix of machines, the layout and the frame and moving-part colours."),
            ("Installation", "Machines go on concrete floor plates or block foundations; the Light line can also stand without anchoring."),
            ("Maintenance", "You get a maintenance plan at handover — inspection and service are recommended twice a year."),
        ],
        "faq": [
            ("Is the equipment certified?", "Yes. The Standard, Light, Plus and Workout lines are tested to DIN EN 16630 for permanently installed outdoor fitness equipment (TÜV Thüringen, certificate no. 3510.02586.Z01). We provide the documentation for the selected machines with the quote."),
            ("How does the weight system work?", "Each machine has weight plates adjusted right on it, so users choose the load like in a gym — from light to serious strength training. The system is patented."),
            ("What is the warranty?", "5 years on the frame (powder or thermoplastic coating), or 10 years with hot-dip galvanising; 3 years on moving metal parts. The warranty applies with regular maintenance as per the manufacturer's instructions."),
            ("Can I choose the colour?", "Yes. Machines come in standard RAL colours, or any RAL colour on request. Frame and moving parts are chosen separately."),
            ("Is there equipment for people with disabilities?", "Yes. The Plus line (9 machines) has a fixed folding seat, so it can also be used by wheelchair users."),
            ("What kind of surface is needed?", "Machines are installed on concrete floor plates or block foundations under the feet; the Light line can also stand without anchoring. We confirm the exact solution after a site visit."),
            ("__procurement__", ""),
            ("__quote__", "The price depends on the machines, quantity, finish and location. Send an enquiry and we will reply with a proposal and a quote."),
        ],
        "ask_p": "Send us the location, the size of the space and who it is for — we reply with an equipment proposal, a layout and a quote.",
        "mail_cat": "Outdoor fitness (StreetBarbell)",
    },
},
}
