# -*- coding: utf-8 -*-
"""Product cards (no prices — specs only, quote on request). Each spec row: (label_me, value_me, label_en, value_en)."""

TEQ = [
    {"img": "teq-one.webp", "title": "TEQ ONE",
     "kind": {"me": "Fiksni · Takmičarski", "en": "Fixed · Competition"},
     "specs": [("Ploča", "HPL, 6 mm", "Top", "HPL, 6 mm"),
               ("Mrežica", "Pleksiglas, 20 mm", "Net", "Plexi, 20 mm"),
               ("Težina", "148 kg", "Weight", "148 kg"),
               ("Fiksiranje", "Za podlogu", "Fixing", "To the ground")]},
    {"img": "teq-smart.webp", "title": "TEQ SMART",
     "kind": {"me": "Sklopivi · Takmičarski", "en": "Foldable · Competition"},
     "specs": [("Ploča", "HPL, 6 mm", "Top", "HPL, 6 mm"),
               ("Sklapanje", "Gasni amortizeri", "Folding", "Gas springs"),
               ("Težina", "168 kg", "Weight", "168 kg"),
               ("Dodatno", "Solo igra", "Extra", "Solo play")]},
    {"img": "teq-lite.webp", "title": "TEQ LITE",
     "kind": {"me": "Sklopivi · Rekreativni", "en": "Foldable · Recreation"},
     "specs": [("Ploča", "Ojačani poliester", "Top", "Reinforced polyester"),
               ("Mrežica", "Polietilen, 15 mm", "Net", "Polyethylene, 15 mm"),
               ("Težina", "110 kg", "Weight", "110 kg"),
               ("Dodatno", "Točkovi + kočnice", "Extra", "Wheels + brakes")]},
    {"img": "teq-x.webp", "title": "TEQ X",
     "kind": {"me": "Fiksni · Rekreativni", "en": "Fixed · Recreation"},
     "specs": [("Ploča", "Ojačani poliester", "Top", "Reinforced polyester"),
               ("Mrežica", "Polietilen, 15 mm", "Net", "Polyethylene, 15 mm"),
               ("Težina", "85 kg", "Weight", "85 kg"),
               ("Fiksiranje", "Za podlogu", "Fixing", "To the ground")]},
]
TEQ_STRIP = {
    "me": ["Unutra / napolju", "Otporno od −20 °C do +40 °C", "Vodootporno i UV otporno",
           "TÜV SÜD sertifikat", "Garancija 24 mjeseca", "Proizvedeno u EU"],
    "en": ["Indoor / outdoor", "Weather-resistant −20 °C to +40 °C", "Waterproof &amp; UV proof",
           "TÜV SÜD certified", "24-month warranty", "Made in EU"],
}

PANELS = [
    {"img": "panel.webp", "title": {"me": "Interaktivna tabla", "en": "Interactive panel"},
     "kind": {"me": "65″ · 75″ · 86″ DLED", "en": "65″ · 75″ · 86″ DLED"},
     "specs": [("Ekran", "4K UHD, 60 Hz", "Display", "4K UHD, 60 Hz"),
               ("Dodir", "20 tačaka, ±1 mm", "Touch", "20 points, ±1 mm"),
               ("Sistem", "Android 14", "System", "Android 14"),
               ("Memorija", "8 GB / 128 GB", "Memory", "8 GB / 128 GB"),
               ("Zvuk", "2 × 20 W", "Audio", "2 × 20 W")]},
    {"img": "kids-table.webp", "title": {"me": "Interaktivni sto", "en": "Interactive table"},
     "kind": {"me": "Za predškolski uzrast", "en": "For preschool age"},
     "specs": [("Ekran", "32″ Full HD", "Display", "32″ Full HD"),
               ("Dodir", "10 tačaka", "Touch", "10 points"),
               ("Sistem", "Android", "System", "Android"),
               ("Memorija", "4 GB / 32 GB", "Memory", "4 GB / 32 GB"),
               ("Napajanje", "12 V, ≤ 60 W", "Power", "12 V, ≤ 60 W")]},
    {"img": "stand-electric.webp", "title": {"me": "Električni stalak", "en": "Electric stand"},
     "kind": {"me": "Mobilni · Podesiva visina", "en": "Mobile · Height adjustable"},
     "specs": [("Za ekrane", "75″–100″", "Fits", "75″–100″"),
               ("Nosivost", "Do 136 kg", "Load", "Up to 136 kg"),
               ("Hod", "500 mm, električni", "Travel", "500 mm, electric"),
               ("Upravljanje", "Daljinski + dodir", "Control", "Remote + touch"),
               ("VESA", "200×200 – 1000×600", "VESA", "200×200 – 1000×600")]},
    {"img": "stand-mobile.webp", "title": {"me": "Mobilni stalak", "en": "Mobile stand"},
     "kind": {"me": "Podni stalak na točkićima", "en": "Floor stand on castors"},
     "specs": [("Za ekrane", "50″–100″", "Fits", "50″–100″"),
               ("Nosivost", "Do 150 kg", "Load", "Up to 150 kg"),
               ("VESA", "Od 1000×600", "VESA", "From 1000×600"),
               ("Ram", "Čelik", "Frame", "Steel"),
               ("Dodatno", "Dvije police", "Extra", "Two shelves")]},
]
PANELS_STRIP = {
    "me": ["Montaža i konfiguracija", "Obuka korisnika", "Garancija 2 godine", "Tehnička podrška",
           "U kutiji: daljinski, 2 olovke, zidni nosač i kabl"],
    "en": ["Installation &amp; configuration", "User training", "2-year warranty", "Technical support",
           "Remote, 2 pens, wall mount and cable in the box"],
}

PLAY = [
    {"img": "play-towers.webp", "title": {"me": "Tematski tornjevi", "en": "Themed towers"},
     "kind": {"me": "Bubbles · Kinglo · Mega · Dino · Flora Play", "en": "Bubbles · Kinglo · Mega · Dino · Flora Play"},
     "specs": [("Za", "Velike površine za igru", "For", "Large play areas"),
               ("Igra", "Penjanje, tobogani, igra uloga", "Play", "Climbing, sliding, role play"),
               ("Izrada", "Čelik, HPL, rotaciono liveni PE", "Build", "Steel, HPL, rotomoulded PE")]},
    {"img": "pr-house.webp", "title": {"me": "Drvene linije", "en": "Wood lines"},
     "kind": {"me": "Robinia Play · Eco", "en": "Robinia Play · Eco"},
     "specs": [("Za", "Parkove i prirodno okruženje", "For", "Parks and natural settings"),
               ("Materijal", "Bagremovo drvo (robinija)", "Material", "Robinia hardwood"),
               ("Izgled", "Netretirano, organski oblici", "Look", "Untreated, organic forms")]},
    {"img": "pr-whale.webp", "title": {"me": "Kompaktno i pojedinačno", "en": "Compact &amp; single"},
     "kind": {"me": "Mini · Single · Active", "en": "Mini · Single · Active"},
     "specs": [("Za", "Mala dvorišta, vrtiće", "For", "Small yards, preschools"),
               ("Uključuje", "Ljuljaške, klackalice, pješčanike", "Includes", "Swings, springers, sandpits"),
               ("Namjena", "Popunjava ili proširuje lokaciju", "Use", "Fills or extends a site")]},
    {"img": "pr-spinner.webp", "title": {"me": "Užad i ravnoteža", "en": "Ropes &amp; balance"},
     "kind": {"me": "Acrobat · Ellipsum · Organiq", "en": "Acrobat · Ellipsum · Organiq"},
     "specs": [("Za", "Stariju djecu, tinejdžere", "For", "Older children, teenagers"),
               ("Igra", "Mreže, ravnoteža, okretanje", "Play", "Net climbing, balance, spinning"),
               ("Izrada", "Čelik i užad", "Build", "Steel and rope structures")]},
    {"img": "play-workout.webp", "title": {"me": "Vježbanje i sport", "en": "Workout &amp; sport"},
     "kind": {"me": "Street Workout · Fitness · Sport", "en": "Street Workout · Fitness · Sport"},
     "specs": [("Za", "Škole, javne prostore", "For", "Schools, public spaces"),
               ("Uključuje", "Kalistenika, outdoor fitness", "Includes", "Calisthenics, outdoor fitness"),
               ("Opcije", "Nerđajući čelik ili robinija", "Options", "Stainless steel or robinia")]},
    {"img": "pr-bench.webp", "title": {"me": "Urbani mobilijar", "en": "Urban furniture"},
     "kind": {"me": "Urbaniq · Aquarius Inox", "en": "Urbaniq · Aquarius Inox"},
     "specs": [("Za", "Trgove, šetališta, parkove", "For", "Squares, promenades, parks"),
               ("Uključuje", "Klupe, korpe, igra sa vodom", "Includes", "Benches, bins, water play"),
               ("Materijal", "Nerđajući čelik", "Material", "Stainless steel")]},
]
PLAY_STRIP = {
    "me": ["HDPE paneli, 15 mm", "Rotaciono liveni PE tobogani i krovovi", "Linija od nerđajućeg čelika",
           "Linija od recikliranih materijala", "Inkluzivna oprema", "Prilagođene modifikacije"],
    "en": ["HDPE panels, 15 mm", "Rotomoulded PE slides and roofs", "Stainless steel line",
           "Recycled line", "Inclusive equipment", "Custom modifications"],
}

FITNESS = [
    {"img": "sb-standard.webp", "title": {"me": "Standard linija", "en": "Standard line"},
     "kind": {"me": "26 sprava · Stojeće vježbe", "en": "26 machines · Standing exercises"},
     "specs": [("Opterećenje", "Patentirani sistem tegova", "Load", "Patented weight system"),
               ("Biomehanika", "Konvergentna i divergentna", "Biomechanics", "Convergent and divergent"),
               ("Izrada", "Nerđajući čelik, gumeni odbojnici", "Build", "Stainless steel, rubber bumpers"),
               ("Primjer", "Chest Press — do 155 kg", "Example", "Chest Press — up to 155 kg")]},
    {"img": "sb-light.webp", "title": {"me": "Light linija", "en": "Light line"},
     "kind": {"me": "22 sprave · Maksimalna stabilnost", "en": "22 machines · Maximum stability"},
     "specs": [("Opterećenje", "Patentirani sistem tegova", "Load", "Patented weight system"),
               ("Montaža", "Moguća i bez ankerisanja", "Installation", "Possible without anchoring"),
               ("Izrada", "Nerđajući čelik", "Build", "Stainless steel"),
               ("Primjer", "Bench Press — do 220 kg", "Example", "Bench Press — up to 220 kg")]},
    {"img": "sb-plus.webp", "title": {"me": "Plus linija", "en": "Plus line"},
     "kind": {"me": "9 sprava · Za korisnike u kolicima", "en": "9 machines · For wheelchair users"},
     "specs": [("Namjena", "Korisnici u kolicima, rehabilitacija", "Purpose", "Wheelchair users, rehabilitation"),
               ("Sjedište", "Fiksno, sklopivo", "Seat", "Fixed, folding"),
               ("Opterećenje", "Dvostepeni sistem", "Load", "Two-level system"),
               ("Pristup", "Široka osnova", "Access", "Wide base")]},
    {"img": "sb-pro.webp", "title": {"me": "PRO linija", "en": "PRO line"},
     "kind": {"me": "12 sprava · Povećano opterećenje", "en": "12 machines · Increased load"},
     "specs": [("Podešavanje", "Brzo i jednostavno", "Adjustment", "Quick and easy"),
               ("Izrada", "Nerđajući čelik, otporno na vandalizam", "Build", "Stainless steel, vandal-resistant"),
               ("Komfor", "Meka sjedišta i valjci", "Comfort", "Soft seats and rollers"),
               ("Primjer", "Multi-Station — do 270 kg", "Example", "Multi-Station — up to 270 kg")]},
    {"img": "sb-workout.webp", "title": {"me": "Workout linija", "en": "Workout line"},
     "kind": {"me": "19 elemenata · Street workout", "en": "19 units · Street workout"},
     "specs": [("Uključuje", "Vratila, ljestve, razboj, zidne ljestve", "Includes", "Bars, ladders, dip bars, wall bars"),
               ("Vježbe", "Zgibovi, sklekovi, propadanja", "Exercises", "Pull-ups, push-ups, dips"),
               ("Izrada", "Čelični stubovi, ojačani spojevi", "Build", "Steel posts, reinforced joints")]},
    {"img": "sb-gym.webp", "title": {"me": "Gymnastic linija", "en": "Gymnastic line"},
     "kind": {"me": "17 sprava · Težina tijela i kardio", "en": "17 machines · Body weight and cardio"},
     "specs": [("Uključuje", "Stepper, veslač, twister, ski walker", "Includes", "Stepper, rower, twister, ski walker"),
               ("Namjena", "Zagrijavanje, istezanje, tonus", "Use", "Warm-up, stretching, toning"),
               ("Za", "Sve uzraste i nivoe", "For", "All ages and levels")]},
    {"img": "sb-kids.webp", "title": {"me": "Kids linija", "en": "Kids line"},
     "kind": {"me": "7 sprava · Za djecu od 6 godina", "en": "7 machines · For children aged 6+"},
     "specs": [("Visina korisnika", "Od 100 cm", "User height", "From 100 cm"),
               ("Uključuje", "Stepper, twister, klatno, leg press", "Includes", "Stepper, twister, pendulum, leg press"),
               ("Izrada", "Manje dimenzije, meka sjedišta", "Build", "Reduced size, soft seats")]},
    {"img": "sb-boxing.webp", "title": {"me": "Boxing linija", "en": "Boxing line"},
     "kind": {"me": "3 sprave · Boks na otvorenom", "en": "3 units · Outdoor boxing"},
     "specs": [("Uključuje", "Vreće i stalci za udarce", "Includes", "Bags and punching stands"),
               ("Materijal", "Ojačani PVC, od −30 do +70 °C", "Material", "Reinforced PVC, −30 to +70 °C"),
               ("Uzrast", "Od 16 godina", "Age", "16+")]},
    {"img": "sb-cardio.webp", "title": {"me": "Cardio linija", "en": "Cardio line"},
     "kind": {"me": "Novo · Bicikli", "en": "New · Bikes"},
     "specs": [("Uključuje", "Ležeći i uspravni bicikl", "Includes", "Recumbent and upright bike"),
               ("Otpor", "Inovativni sistem otpora", "Resistance", "Innovative resistance system"),
               ("Dizajn", "Sa Ciclotte i Lucom Schieppatijem", "Design", "With Ciclotte and Luca Schieppati")]},
]
FITNESS_STRIP = {
    "me": ["DIN EN 16630 · TÜV Thüringen", "Patentirani sistem tegova", "Boja po izboru (RAL)",
           "Plastifikacija, termoplastika ili vruće cinkovanje", "Garancija na ram 5–10 godina", "QR video uputstva"],
    "en": ["DIN EN 16630 · TÜV Thüringen", "Patented weight system", "Any RAL colour",
           "Powder, thermoplastic or hot-dip galvanised", "5–10-year frame warranty", "QR video guides"],
}
