# -*- coding: utf-8 -*-
"""Homepage strings. EN matches the live site; ME is the new default."""

HOME = {
"me": {
    "title": "5TO9 — Sport, obrazovanje i javni prostori | Podgorica",
    "desc": "5TO9 isporučuje integrisana rješenja za sport, obrazovanje i javne prostore — nabavka opreme, montaža i realizacija projekta u jednom procesu. Teqball stolovi, interaktivne table, dječija igrališta i outdoor fitness. Podgorica, Crna Gora.",
    "nav": [("#about", "O nama"), ("#offer", "Ponuda"), ("#sports", "Sport"), ("#digital", "Digitalno"),
            ("#playgrounds", "Igrališta"), ("#fitness", "Fitness"), ("#process", "Kako radimo")],
    "mm": [("#about", "O nama"), ("#offer", "Ponuda"), ("#sports", "Sport"), ("#digital", "Digitalno"),
           ("#playgrounds", "Igrališta"), ("#fitness", "Outdoor fitness"), ("#process", "Kako radimo"), ("#contact", "Kontakt")],
    "rail": [("about", "O NAMA"), ("offer", "PONUDA"), ("sports", "SPORT"), ("digital", "DIGITALNO"),
             ("playgrounds", "IGRALIŠTA"), ("fitness", "FITNESS"), ("process", "METOD"), ("contact", "KONTAKT")],
    "hero_line": "Integrisana rješenja za <b>sport, obrazovanje i javne prostore</b> — nabavka opreme, montaža i realizacija projekta u jednom procesu.",
    "scroll": "Skrolujte",
    "place": "Podgorica, Crna Gora",
    "ticker": ["300+ instaliranih stolova", "100+ interaktivnih tabli", "Škole", "Opštine", "Javni prostori"],
    "who_eyebrow": "Kompanija",
    "who_h": "KO<br>SMO MI",
    "who_lede": "5TO9 isporučuje integrisana rješenja za sport, obrazovanje i javne prostore, objedinjujući nabavku opreme, montažu i realizaciju projekta u jedan efikasan proces.",
    "pillars_eyebrow": "Četiri oblasti rada",
    "pillars": ["Sportska infrastruktura i oprema", "Digitalna rješenja", "Igrališta i otvoreni prostori", "Outdoor fitness"],
    "sports_alt": "Brendirani TEQ sto pored osvijetljenog sportskog terena u Podgorici",
    "sports_tag": "Naša rješenja — P1",
    "sports_h": "Sportska infrastruktura<br>i oprema",
    "sports_p": [
        "5TO9 razvija i isporučuje multifunkcionalne sportske prostore za škole, opštine i javne površine. Kombinacijom projektovanja infrastrukture, nabavke opreme i realizacije na terenu, projekti postaju trajni i često korišćeni sadržaji zajednice.",
        "Rješenja obuhvataju višenamjenske sportske podloge, integrisane zone za aktivnosti i montažu sportske opreme, prilagođene različitim grupama korisnika i veličini prostora.",
        "Svaki projekat je osmišljen tako da stvori funkcionalan, pristupačan i dugotrajan prostor za svakodnevnu upotrebu, koji doprinosi razvoju lokalne zajednice.",
    ],
    "range_eyebrow": "Oprema · TEQ stolovi",
    "range_h": "ZAKRIVLJENI STO,<br>ČETIRI MODELA.",
    "range_p": "Svaki model je dimenzija 3 × 1,5 m i visine 0,76 m, za unutrašnju i spoljašnju upotrebu. Izbor zavisi od toga da li sto stoji fiksno ili se pomjera i da li služi za takmičenja ili rekreaciju.",
    "fit_alt": "Plave StreetBarbell sprave sa tegovima u natkrivenoj outdoor teretani",
    "fit_tag": "Naša rješenja — P4",
    "fit_h": "Outdoor fitness<br>sa pravim tegovima",
    "fit_p": [
        "5TO9 isporučuje i montira outdoor teretane finskog proizvođača StreetBarbell — sprave sa patentiranim sistemom tegova, ispitane po standardu EN 16630, za parkove, škole, kampuse, hotele i stambene komplekse.",
        "Kombinujemo sprave za snagu, street workout konstrukcije, inkluzivnu Plus liniju za korisnike u invalidskim kolicima i Kids liniju za najmlađe — u rasporedu i bojama koji odgovaraju prostoru.",
    ],
    "digital_alt": "Primopredaja interaktivne table u vrtiću",
    "digital_tag": "Naša rješenja — P2",
    "digital_h": "Digitalna rješenja",
    "digital_p": [
        "5TO9 nudi savremena digitalna rješenja koja unapređuju komunikaciju, učenje i saradnju u obrazovnim ustanovama, institucijama i firmama. Spajanjem napredne opreme sa montažom i podrškom korisnicima, svako rješenje se isporučuje kao kompletan sistem spreman za upotrebu.",
        "Ponuda obuhvata interaktivne ekrane i prilagodljiva rješenja koja se lako uklapaju u različite prostore, za efikasne prezentacije, obuke i svakodnevni rad.",
        "Svako rješenje se prilagođava konkretnim potrebama korisnika, uz pouzdanost, jednostavnost upotrebe i dugoročnu funkcionalnost.",
        "Nakon montaže naš tim uživo obučava nastavnike i zaposlene, kako bi se table koristile svakog dana.",
    ],
    "panels_eyebrow": "Oprema · GAOKEview",
    "panels_h": "INTERAKTIVNE TABLE<br>I NOSAČI.",
    "panels_p": "Table stižu podešene, montirane i spremne za čas — montaža, obuka zaposlenih i podrška tokom garantnog roka su uključeni.",
    "play_alt": "Djeca se igraju na inkluzivnom igralištu",
    "play_tag": "Naša rješenja — P3",
    "play_h": "Igrališta i<br>otvoreni prostori",
    "play_p": [
        "5TO9 razvija i isporučuje otvorene prostore namijenjene bezbjednom, funkcionalnom i zanimljivom korišćenju u zajednici. Kroz planiranje, izbor opreme i realizaciju, svaki prostor se prilagođava potrebama korisnika i okruženju.",
        "Rješenja su usmjerena na pristupačne i dugotrajne prostore koji podstiču fizičku aktivnost, druženje i dugoročnu upotrebu, i podižu kvalitet javnih i zajedničkih površina.",
    ],
    "playrange_eyebrow": "Oprema · Buglo Play",
    "playrange_h": "IGRALIŠTA,<br>LINIJU PO LINIJU.",
    "playrange_p": "Katalog sa više od dvadeset linija proizvoda, od jedne klackalice na opruzi do kompletnog tematskog tornja — uz prilagođene modifikacije kada lokacija traži nešto što još ne postoji.",
    "process_eyebrow": "Metod",
    "process_h": "KAKO RADIMO",
    "steps": [("Koncept", "Razumijevanje prostora, potreba korisnika i ciljeva projekta."),
              ("Planiranje", "Izrada prilagođenih rješenja, rasporeda i tehničkih specifikacija."),
              ("Isporuka", "Nabavka opreme i montaža na terenu."),
              ("Aktivacija", "Edukacija korisnika i promotivna podrška kako bi svako rješenje bilo prihvaćeno i efikasno korišćeno.")],
    "process_big": "JEDAN<br>PARTNER,<br><em>ČETIRI</em><br>KORAKA.",
    "process_note": "Od prvog obilaska lokacije do dana kada ljudi počnu da koriste prostor — sve na jednom mjestu.",
    "work_eyebrow": "U brojkama",
    "work_h": "ISPORUČENO,<br>NE SAMO PONUĐENO.",
    "work_lede": "Oprema isporučena i montirana za škole, vrtiće i opštine.",
    "stats": [("300+", "Instaliranih stolova"), ("100+", "Instaliranih interaktivnih tabli"), ("24 mj.", "Garancija na opremu")],
    "offer_eyebrow": "Šta nudimo",
    "offer_h": "IZABERITE<br>KATEGORIJU.",
    "offer_p": "Svaka kategorija ima svoju stranicu sa modelima, specifikacijama i odgovorima na najčešća pitanja.",
    "contact_eyebrow": "Kontakt",
    "contact_h": "IZGRADIMO<br><em>PROSTOR</em><br>ZAJEDNO.",
    "more": {"sports": [("teqball", "Teqball stolovi →")],
             "fitness": [("fitness", "Outdoor fitness →")],
             "digital": [("panels", "Interaktivne table →")],
             "play": [("playgrounds", "Dječija igrališta →")]},
},
"en": {
    "title": "5TO9 — Sport, education and public spaces | Podgorica, Montenegro",
    "desc": "5TO9 delivers integrated solutions for sport, education and public spaces — equipment supply, installation and project execution in one streamlined process. Teqball tables, interactive displays, playgrounds and outdoor fitness. Podgorica, Montenegro.",
    "nav": [("#about", "Who we are"), ("#offer", "Range"), ("#sports", "Sports"), ("#digital", "Digital"),
            ("#playgrounds", "Playgrounds"), ("#fitness", "Fitness"), ("#process", "How we work")],
    "mm": [("#about", "Who we are"), ("#offer", "Range"), ("#sports", "Sports"), ("#digital", "Digital"),
           ("#playgrounds", "Playgrounds"), ("#fitness", "Outdoor fitness"), ("#process", "How we work"), ("#contact", "Contact")],
    "rail": [("about", "WHO WE ARE"), ("offer", "RANGE"), ("sports", "SPORTS"), ("digital", "DIGITAL"),
             ("playgrounds", "PLAYGROUNDS"), ("fitness", "FITNESS"), ("process", "METHOD"), ("contact", "CONTACT")],
    "hero_line": "Integrated solutions for <b>sport, education and public spaces</b> — equipment supply, installation and project execution in one streamlined process.",
    "scroll": "Scroll",
    "place": "Podgorica, Montenegro",
    "ticker": ["300+ tables installed", "100+ interactive panels", "Schools", "Municipalities", "Public spaces"],
    "who_eyebrow": "The company",
    "who_h": "WHO<br>WE ARE",
    "who_lede": "5TO9 delivers integrated solutions for sport, education and public spaces, combining equipment supply, installation and project execution into one streamlined process.",
    "pillars_eyebrow": "Four areas of work",
    "pillars": ["Sports Infrastructure &amp; Equipment", "Digital Solutions", "Playgrounds &amp; Outdoor Spaces", "Outdoor Fitness"],
    "sports_alt": "Branded TEQ table beside a floodlit sports court in Podgorica",
    "sports_tag": "Our solutions — P1",
    "sports_h": "Sports Infrastructure<br>&amp; Equipment",
    "sports_p": [
        "5TO9 develops and delivers multifunctional sports environments designed for schools, municipalities and public spaces. Through a combination of infrastructure design, equipment supply and on-site implementation, projects are transformed into durable, high-usage community assets.",
        "The solutions include multi-sport surfaces, integrated activity zones and installation of sports equipment, adapted to different user groups and space capacities.",
        "Each project is designed to create functional, accessible and long-lasting spaces that support everyday use and contribute to the development of local communities.",
    ],
    "range_eyebrow": "Equipment · TEQ tables",
    "range_h": "THE CURVED<br>TABLE, FOUR WAYS.",
    "range_p": "Every model is 3 × 1.5 m at 0.76 m height, built for indoor and outdoor use. The choice comes down to whether the table stays put or moves, and whether it is used for competition or recreation.",
    "fit_alt": "Blue StreetBarbell plate-loaded machines in a covered outdoor gym",
    "fit_tag": "Our solutions — P4",
    "fit_h": "Outdoor fitness<br>with real weights",
    "fit_p": [
        "5TO9 supplies and installs outdoor gyms by Finnish manufacturer StreetBarbell — machines with a patented weight system, tested to EN 16630, for parks, schools, campuses, hotels and residential complexes.",
        "We combine strength machines, street workout structures, the inclusive Plus line for wheelchair users and the Kids line for the youngest — in a layout and colours that suit the space.",
    ],
    "digital_alt": "Interactive display handed over at a preschool",
    "digital_tag": "Our solutions — P2",
    "digital_h": "Digital Solutions",
    "digital_p": [
        "5TO9 provides modern digital solutions designed to enhance communication, learning and collaboration across educational, institutional and business environments. By combining advanced equipment with installation and user support, each solution is delivered as a complete and ready-to-use system.",
        "The offer includes interactive display technologies and adaptable setups that integrate seamlessly into different spaces, supporting efficient presentations, training and everyday operations.",
        "Each solution is tailored to the specific needs of the user, ensuring reliability, ease of use and long-term functionality.",
        "After installation our team trains teachers and staff in person, so the panels are used every day.",
    ],
    "panels_eyebrow": "Equipment · GAOKEview",
    "panels_h": "INTERACTIVE PANELS<br>AND MOUNTS.",
    "panels_p": "Panels arrive configured, mounted and ready for a lesson — installation, staff training and support during the warranty period are included.",
    "play_alt": "Children playing on an accessible playground",
    "play_tag": "Our solutions — P3",
    "play_h": "Playgrounds &amp;<br>Outdoor Spaces",
    "play_p": [
        "5TO9 develops and delivers outdoor environments designed to support safe, functional and engaging community use. Through a combination of planning, equipment selection and implementation, each space is adapted to the specific needs of its users and surroundings.",
        "The solutions focus on creating accessible and durable environments that encourage physical activity, social interaction and long-term use, contributing to the overall quality of public and shared spaces.",
    ],
    "playrange_eyebrow": "Equipment · Buglo Play",
    "playrange_h": "PLAYGROUNDS,<br>LINE BY LINE.",
    "playrange_p": "A catalogue of more than twenty product lines, from a single spring rider to a full themed play tower — plus custom modifications when the site asks for something that does not exist yet.",
    "process_eyebrow": "Method",
    "process_h": "HOW WE WORK",
    "steps": [("Concept", "Understanding the space, user needs and project objectives."),
              ("Planning", "Developing tailored solutions, layouts and technical specifications."),
              ("Delivery", "Supplying equipment and executing installation on site."),
              ("Activation", "Providing user education and promotional support to ensure full adoption and effective use of each solution.")],
    "process_big": "ONE<br>PARTNER,<br><em>FOUR</em><br>STEPS.",
    "process_note": "From the first site visit to the day people start using the space — handled end to end.",
    "work_eyebrow": "In numbers",
    "work_h": "DELIVERED,<br>NOT PROPOSED.",
    "work_lede": "Equipment supplied and installed for schools, preschools and municipalities.",
    "stats": [("300+", "Tables installed"), ("100+", "Interactive panels installed"), ("24 mo", "Warranty on equipment")],
    "offer_eyebrow": "What we offer",
    "offer_h": "CHOOSE A<br>CATEGORY.",
    "offer_p": "Each category has its own page with models, specifications and answers to the most common questions.",
    "contact_eyebrow": "Contact",
    "contact_h": "LET'S BUILD<br>THE <em>SPACE</em>.",
    "more": {"sports": [("teqball", "Teqball tables →")],
             "fitness": [("fitness", "Outdoor fitness →")],
             "digital": [("panels", "Interactive displays →")],
             "play": [("playgrounds", "Playgrounds →")]},
},
}
